version: '3.1'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://MYSQL:3306/events?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

services:
  db:
    image: mysql
    container_name: MYSQL
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - events_data:/var/lib/mysql

  webevents:
    image: luizfilipebp/microservice.webevents.consumer
    container_name: WebConsumer
    ports:
      - "8080:8080"
    environment:
      <<: *database-variables
    depends_on:
      - db
    links:
      - db

volumes:
  events_data: